### ISSUE TITLE
Travis-CI

### ISSUE THREAD

**Issue by Endle** [RainGhost/boinc#2]
我测试了一下，发现用旧版本的怎么搞都不行，但是官方最新的版本就可以编译
<https://travis-ci.org/Endle/boinc/builds/446520472>
个人猜测，是不是在这段时间里官方修了一些编译过程的bug？如果是的，个人建议切换到最新版，然后把你写过的代码cherry-pick过来

**Comment by runninghyk** [comment]
我估计就是我之前操作不当造成的，我想下载他特定的版本之后再做修改的。
就直接在release上下载，之后再通过Github for Windows上传了。
觉得肯定是缺了很多东西才会这样的。

**Comment by Endle** [comment]
那就直接切换到 7.14.2 好了
<https://travis-ci.org/Endle/boinc>
貌似7.14.2在travis ci上工作正常

**Comment by Endle** [comment]
我认为我找到原因了

代码中，有很多类似 `version.h.in` 的文件。但是，`.gitignore`却有
```
## files created by _autosetup (autoreconf):
*.in
*.in~
```
个人猜测，upstream 使用了 `git add -f` 之类的方式将这些配置文件强行提交

我能想到的最简单的办法，是从官方源fork出来以后，cherry-pick，再 push --force 到 RainGhost/master

**Comment by runninghyk** [comment]
最后的结果不是很好。可能还是存在一些小问题。

**Comment by Endle** [comment]
> 最后的结果不是很好。可能还是存在一些小问题。
> https://travis-ci.org/RainGhost/boinc

问题就是我上文提到的， `.gitignore` 的问题

**Comment by Endle** [comment]
<https://github.com/RainGhost/boinc/commit/6a51e177443fca74237f3a41af6e5f37268ffe01>

问题应该是解决了
